# Generated by Django 2.1.1 on 2019-02-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190201_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptainsReport',
        ),
    ]
