# Generated by Django 2.1.1 on 2019-02-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_delete_captainsreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCaptainPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('player_name', models.TextField(blank=True, null=True)),
                ('total_points', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_captain_points',
                'managed': False,
            },
        ),
    ]
